//
//  WelcomeViewController.swift
//  RefugeConnect
//
//  Created by Christian Graver on 02/03/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

class WelcomeViewController: UIViewController {
	
	// MARK: - Outlets
	@IBOutlet var refugeeButton: UIButton! {
		didSet {
			refugeeButton.setTitle("I'm a refugee", for: UIControl.State())
			refugeeButton.setTitleColor(.systemYellow, for: UIControl.State())
			refugeeButton.titleLabel?.font = .boldSystemFont(ofSize: 18)
		}
	}
	@IBOutlet var friendButton: UIButton! {
		didSet {
			friendButton.setTitle("I think I can help a refugee", for: UIControl.State())
			friendButton.setTitleColor(.systemBlue, for: UIControl.State())
			friendButton.titleLabel?.font = .boldSystemFont(ofSize: 18)
		}
	}
	
	// MARK: - Properties
	private var server: ServerRepository!
	
	// MARK: - Init
	class func instantiate(server: ServerRepository) -> WelcomeViewController {
		let name = "\(WelcomeViewController.self)"
		let storyboard = UIStoryboard(name: name, bundle: nil)
		let vc = storyboard.instantiateViewController(withIdentifier: name) as! WelcomeViewController
		vc.server = server
		return vc
	}
	
	// MARK: - View lifecycle
	override func viewDidLoad() {
		super.viewDidLoad()
	}
	
	// MARK: - Actions
	@IBAction func refugeePressed(_ sender: Any) {
		let findSheltherVC = FindShelterViewController.instantiate(server: server)
		self.navigationController?.pushViewController(findSheltherVC, animated: true)
	}
	
	@IBAction func friendPressed(_ sender: Any) {
		let createSheltherVC = CreateShelterViewController.instantiate(server: server)
		self.navigationController?.pushViewController(createSheltherVC, animated: true)
	}
	// MARK: - Misc
	private func setupView() {
		
	}
}
