//
//  FindShelterViewController.swift
//  RefugeConnect
//
//  Created by Christian Graver on 02/03/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

class FindShelterViewController: UIViewController {
	
	// MARK: - Outlets
	
	// MARK: - Properties
	var server: ServerRepository!
	
	// MARK: - Init
	class func instantiate(server: ServerRepository) -> FindShelterViewController {
		let name = "\(FindShelterViewController.self)"
		let storyboard = UIStoryboard(name: name, bundle: nil)
		let vc = storyboard.instantiateViewController(withIdentifier: name) as! FindShelterViewController
		vc.server = server
		return vc
	}
	
	// MARK: - View lifecycle
	override func viewDidLoad() {
		super.viewDidLoad()
	}
	
	// MARK: - Actions
	
	// MARK: - Misc
}
